### PR TITLE
bumped deps

### PR DESCRIPTION
**Pull request by dmg3**
dependabot updates

### CODE REVIEW

**Comment by dmg3** [comment]
https://app.shortcut.com/gamechangermedia/story/260646/merge-passing-dependabot-prs-2022-11-07

**Comment by dmg3** [comment]
@matt-casey When do we usually create a release for this package?

**Comment by odielleongc** [comment]
I think, usually when the main deps change we would like a new version, but in this case the upgrade is only for the dev dependencies. I don't see a need to make a new release.

**Comment by odielleongc** [comment]
Do we need the `package-lock.json` file?

**Comment by dmg3** [comment]
> Do we need the `package-lock.json` file?

Oops, thanks, didn't notice that. I removed it and added a git ignore for it

**Pull request merged**
